#!/usr/bin/env bash 
# Script display the username, user ID, and home directory path for the user, for the file /etc/passwd

while IFS=: read -r username _ _ uid _ homedir _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $homedir"
done < /etc/passwd
