#!/usr/bin/env bash 
# Script to tell the story of /etc/passwd.

while IFS=: read -r username password uid gid gecos homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: UID: $uid, GECOS: $gecos"
done < /etc/passwd
