#!/usr/bin/env bash
# Script to display numbers from 1 to 20 and messages based on loop iteration.

count=1
while [ $count -le 20 ]
do 
    case $count in
        4) echo "$count"; echo "bad luck from China" ;;
        9) echo "$count"; echo "bad luck from Japan" ;;
        17) echo "$count"; echo "bad luck from Italy" ;;
