#!/usr/bin/env bash 
# Script to give information about the school file.

if [ -f school ]; then
    echo "school file exists"
    if [ ! -s school ]; then
        echo "school file is empty"
    else 
        echo "school file is not empty"
    fi
    echo "school is a regular file"
else 
    if [ -e school ]; then
        echo "The 'school' entity exists but it's not a regular file."
    else 
        echo "school file does not exist"
fi
