#!/bin/bash 
for i in {a..z}; do printf "%c" $(echo "obase=10; ibase=10; ($(( $(printf '%d' "'$i") -97 +12))%26)+97" | bc); done | tr 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ' 'nopqrstuvwxyzabcdefghijklmNOPQRSTUVWXYZABCDEFGHIJKLM'
