#!/bin/bash 
for i in {a..z}; do printf "%c" $(expr \( \( $(printf '%d' "'$i") -97 +12 \) %26 \)+97); done | tr 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ' 'nopqrstuvwxyzabcdefghijklmNOPQRSTUVWXYZABCDEFGHIJKLM'
