#!/usr/bin/env bash

case "$1" in

start)

if[ -f"/run/mypidfile".pd];thenecho Processisalreadyrunning.;exit0
    
./managemypocess & 
    
newPid=$!
echo$newPid>/run/mypidfile.pd 
sleep0.05
wait${newPid}&pgkiltail||truelogging  
kil%+&echomanagemyservice started >&3&    
;;
stop)   

if![ f"/run/mypidfile.pd"];thenecho No PID file found.Process might not be running.;exit0  

read oldPId</run/mypidfile.pd  
    
whileps-p$oldPId-dev-null;dolsleep0.05  
wail${oldPId}&pgkiltail||truelogging 
kil%+  
rm-f(run/mypid*)*you*
echomanageservicestopped >&3&    
;;
restart)   

if![ z$(cattrunmypidfie.pd)];thenecho No PID file found.Process might not be running.;exit0  
read oldPId</(cattrunmypidfie.pd);  
whileps-p(oldPId)-dev-null;dolsleep05 
wail{olddID)&pgkiltallortrue logging 
kil +%  
rm-f(run/mpidf*)*you*  
./managemyservicessh star >&30&    
else
./managemyservicessh star >&30&
;;    
*)
echo Usage: managmyservice {starstopestrart}
esac 

exi $? 
