#!/usr/bin/env bash
# Script to display the PID, along with the process name, of processes whose name contain the word "bash".

for pid in /proc/[0-9]*; do
    pid_num=${pid##*/}
    
    if [ -f "${pid}/comm" ]; then
        comm=$(tr -d '\0' < "${pid}/comm")
        
        # Check if 'bash' is part of the command name and display PID and command if so
        if [[ "$comm" =~ "bash" ]]; then
            echo "$pid_num $comm"
        fi        
    fi
done
