#!/usr/bin/env bash
# Script to iterate over all PIDs in/proc then stop the '4-to_infinity_and_beyond' process using kill.

found=false

for pid in /proc/[0-9]*; do
    pid_num=${pid##*/}
    
    if [ -f "${pid}/comm" ]; then
        comm=$(tr -d '\0' < "${pid}/comm")

        if [[ "$comm" =~ "4-to_infinity_and_beyond" ]]; then
            kill "$pid_num"

	    found=true
	    break  
        fi  
    fi
done 
