#!/usr/bin/env bash
# Script to stop the '4-to_infinity_and_beyond' process using kill.

for pid in /proc/[0-9]*; do
    pid_num=${pid##*/}
    
    if [ -f "${pid}/comm" ]; then
        comm=$(tr -d '\0' < "${pid}/comm")

        if [[ "$comm" =~ "4-to_infinity_and_beyond" ]]; then
            kill "$pid"
            exit 0  
        fi  
    fi
done
exit 1 > /dev/null 2>&1 
