#!/usr/bin/env bash
# Script to stop the '4-to_infinity_and_beyond' process using kill.

pid=$(ps -ef | grep -v grep | grep 4-to_infinity_and_beyond | awk '{print $2}')

if [ -n "$pid" ]; then
    kill $pid
fi
