#!/usr/bin/env bash
# Script to stop 4-to_infinity_and_beyond process.

pid=$(ps -ef | grep -v grep | grep 4-to_infinity_and_beyond | awk '{print $2}')

if [ -n "$pid" ]; then

    /bin/sh -c "echo 15 > /proc/$pid/signal"
    
fi
