#!/usr/bin/env bash
# Script to stop 4-to_infinity_and_beyond process.

pid=$(pgrep -f 4-to_infinity_and_beyond)

if [ -z "$pid" ]; then

    # If PID of 4-to_infinity_and_beyond not found, start process in background and get its PID immediately.
    (while true; do echo "To infinity and beyond"; sleep 1; done) &
    pid=$!
fi
pkill -9 "$pid"
