#!/usr/bin/env bash
# Script to stop 7-highlander process

while true; do
    
    if ! pgrep -f 4-to_infinity_and_beyond; then
        
        # If not running, start it in background.
        (while true; do echo "To infinity and beyond"; sleep 1; done) &
        sleep 0.5  
    fi
    pkill -9 -f 4-to_infinity_and_beyond
done
